#!/bin/sh

make lint-git

STAGED_MOVE_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.move$')

if [ -z "$STAGED_MOVE_FILES" ]; then
    echo "No Move files to format."
    exit 0
fi

prettier-move $STAGED_MOVE_FILES --write
git add $STAGED_MOVE_FILES
